video_path: ../data/video4.mp4
output_video_path: ../data/video4_result_trt.mp4

detection&keypoint:
  model_path: ../weights/kapao/kapao_s_coco_1280_3.trt
  cfg_path: ./detection_keypoint/kapao/coco-kp.yaml

action_recognition:
  model_path: ../weights/stgcn/tsstg-model.pth

device: 'cuda:0'